### ISSUE TITLE
CustomVision onnxruntime openvino

### ISSUE THREAD

**Issue by amarrmb** [Azure-Samples/onnxruntime-iot-edge#15]
I have following use-case:
1) Want to use customvision.ai to train a model
2) Want to export a model as ONNX. Note that customvision.ai supports ONNX for windows
3) Convert the ONNX model to openvino OR use openvino's ONNX runtime

Is this possible? Does customvision.ai's ONNX model be able to run on a Ubuntu openvino installation? Or do i have to use like Azure ML to write/train an ONNX compatible model?

**Comment by manashgoswami** [comment]
You can use the ONNX model from CustomVision.ai directly to run with ONNX Runtime + OpenVINO.

[This NB](https://github.com/Azure-Samples/onnxruntime-iot-edge/blob/master/AzureML-OpenVINO/AML-BYOC-ONNXRUNTIME-OpenVINO.ipynb) shows the example to import a pretrained ONNX model to run on the device with openVINO.

**Comment by shre2398** [comment]
> You can use the ONNX model from CustomVision.ai directly to run with ONNX Runtime + OpenVINO.
> 
> [This NB](https://github.com/Azure-Samples/onnxruntime-iot-edge/blob/master/AzureML-OpenVINO/AML-BYOC-ONNXRUNTIME-OpenVINO.ipynb) shows the example to import a pretrained ONNX model to run on the device with openVINO.

Is UP(squared) device mandatory for the onnxruntime iotedge using openVino?

**Comment by manashgoswami** [comment]
This sample could work with other HW using the OpenVINO sdk. Some config options might have to change however.

**Comment by ksaye** [comment]
@manashgoswami  would love any help on how to adapt the standard CustomVision code to work on the OpenVINO + Movidius.  I am getting the error:

> root@home:/code# python onnxruntime_predict.py 1.jpg
> 2020-05-11 21:10:42.307032
> 2020-05-11 21:10:45.550660
> Traceback (most recent call last):
>   File "onnxruntime_predict.py", line 61, in <module>
>     main(sys.argv[1])
>   File "onnxruntime_predict.py", line 52, in main
>     predictions = od_model.predict_image(image)
>   File "/code/object_detection.py", line 126, in predict_image
>     prediction_outputs = self.predict(inputs)
>   File "onnxruntime_predict.py", line 41, in predict
>     return np.squeeze(outputs).transpose((1,2,0)).astype(np.float32)
> ValueError: axes don't match array

when using a onnx file from CustomVision.ai.

This seems to happen with:

- mcr.microsoft.com/azureml/onnxruntime:latest-openvino-cpu
- mcr.microsoft.com/azureml/onnxruntime:latest-openvino-myriad

but not with: 

- mcr.microsoft.com/azureml/onnxruntime:latest

Here are the sets to reproduce:

Hardware:
Up2 with AI option or a standard PC with Movidius USB stick (both show the same issue) running Ubuntu 18.04

Steps to reproduce:

- docker run -i -t --rm --net=host --name onnx --privileged -v /dev:/dev mcr.microsoft.com/azureml/onnxruntime:latest-openvino-cpu bash
- DEBIAN_FRONTEND=noninteractive
- apt-get update && apt-get install libssl-dev libffi-dev libgtk2.0-dev python3-pip --yes
- pip install --upgrade pip
- pip install azure-storage && pip install flask opencv-python &&  pip install pytz && pip install pillow
- \# this is a download of a default ONNX from CustomVision.ai
- wget https://kevinsayazstorage.blob.core.windows.net/public/d64f43ac870a437497ce47721d95301d.ONNX.zip
- wget https://kevinsayazstorage.blob.core.windows.net/public/1.jpg
- unzip d64f43ac870a437497ce47721d95301d.ONNX.zip
- python python/onnxruntime_predict.py 1.jpg

**Comment by ksaye** [comment]
All, through the help of many people associated with this project, I am able to get an ONNX model created via CustomVision.ai to work amazingly fast on Movidius using OpenVINO.  I did a quick 5 step writeup here: [CustomVision + ONNX + OpenVINO + MovidiusX](https://kevinsaye.wordpress.com/2020/05/13/customvision-accelerating-an-onnx-model-on-a-movidius-network-compute-stick/) for others who want to try it out.  Thanks @manashgoswami and others of the amazing help.

**Comment by manashgoswami** [comment]
Thanks this article. Good summary of the steps.
