### ISSUE TITLE
Failed on Jetson Xavier inside inferencemodule with onnxruntime error: "Cannot load onnxruntime.capi..."

### ISSUE THREAD

**Issue by guybartal** [Azure-Samples/onnxruntime-iot-edge#17]
```
gubert@guy-xavier:~$ sudo iotedge logs inferencemodule:

/usr/local/lib/python3.6/dist-packages/onnxruntime/capi/_pybind_state.py:13: UserWarning: Cannot load onnxruntime.capi. Error: 'libnvinfer.so.5: cannot open shared object file: No such file or directory'
  warnings.warn("Cannot load onnxruntime.capi. Error: '{0}'".format(str(e)))
Traceback (most recent call last):
  File "./main.py", line 12, in <module>
    import onnxruntime as rt
  File "/usr/local/lib/python3.6/dist-packages/onnxruntime/__init__.py", line 21, in <module>
    from onnxruntime.capi._pybind_state import RunOptions, SessionOptions, set_default_logger_severity, get_device, NodeArg, ModelMetadata
ImportError: cannot import name 'RunOptions'
```

**Comment by manashgoswami** [comment]
@jywu-msft can you take a look at this one?

**Comment by jywu-mysoft** [comment]
error shows Error: 'libnvinfer.so.5: cannot open shared object file: No such file or directory

that shared lib is located in /usr/lib/aarch64-linux-gnu
can you try adding that location to the PATH?

**Comment by corymast** [comment]
I received the same error and adding /usr/lib/aarch64-linux-gnu to the PATH did not solve the issue. I did see that there was a libnvinfer.so.6 file in the /usr/lib/aarch64-linux-gnu directory that was symlinked to libnvinfer.so.6.0.1 so I decided to create a new symlink to libnvinfer.so.6.0.1 named libnvinfer.so.5 in that same directory using the following command

`sudo ln -s libnvinfer.so.6.0.1 libnvinfer.so.5`

While this may not be the correct way to solve this issue, it did get me past the issue and ultimately I was able to get the application working.

Hope this helps!

**Comment by jywu-mysoft** [comment]
> I received the same error and adding /usr/lib/aarch64-linux-gnu to the PATH did not solve the issue. I did see that there was a libnvinfer.so.6 file in the /usr/lib/aarch64-linux-gnu directory that was symlinked to libnvinfer.so.6.0.1 so I decided to create a new symlink to libnvinfer.so.6.0.1 named libnvinfer.so.5 in that same directory using the following command
> 
> `sudo ln -s libnvinfer.so.6.0.1 libnvinfer.so.5`
> 
> While this may not be the correct way to solve this issue, it did get me past the issue and ultimately I was able to get the application working.
> 
> Hope this helps!

the version of onnxruntime you're using has dependency on TensorRT 6 (thus it's looking for libnvinfer.so.6, rather than libnvinfer.so.5)
onnxruntime 0.5.0 depends on TensorRT 5.x whereas onnxruntime 1.0 and 1.1 depends on TensorRT 6.x
Looks like Jetpack 4.3 comes with TensorRT 6 and earlier versions included TensorRT 5.
Your workaround might work for your application, but there's risk of abi incompatibility due to major version change. 
If you need to use TensorRT 6, it would be safer to build a newer version of onnxruntime.

**Comment by manashgoswami** [comment]
@corymast We have updated this sample to use the new Jetpack 4.4 image. Can you please retry the sample and send your feedback.
