### ISSUE TITLE
Confusion in local blob storage steps

### ISSUE THREAD

**Issue by kaushikCanada** [Azure-Samples/onnxruntime-iot-edge#25]
Hi,
I am referring to the text in https://github.com/Azure-Samples/onnxruntime-iot-edge/blob/master/README-ONNXRUNTIME-arm64.md#cloud-storage . I am following the ssteps, but am confused as to which name and connection string to use where. there seem to be two sets of connections(cloud blob + local blob). these are the 4 steps where im gettign confused in. please help clarify.

- Change the cloudStorageConnectionString variable to your cloud storage connection where it has "<insert cloud storage connection string here>". You can find the connection string on the portal in your storage account under the Access Keys tab.

- Change the variable LOCAL_STORAGE_ACCOUNT_NAME to the container you created in your storage account during phase one (i.e. storagetestlocal).

- Change the variable LOCAL_STORAGE_ACCOUNT_KEY to your generated local storage account key. You can use this generator here.

- In the InferenceModule directory, in main.py adjust the variable block_blob_service to hold the connection string to the local blob storage account. You can find information about configuring connection strings here or just replace the given < > with what is required.

**Comment by oliviajain** [comment]
You created a **storage account** and a **container** within that storage account in [phase 1](https://github.com/Azure-Samples/onnxruntime-iot-edge/blob/master/README-Setup.md#create-a-storage-account-and-storage-container): 

cloudStorageConnectionString is the connection string of the **storage account**. 

LOCAL_STORAGE_ACCOUNT_NAME is the name of the **storage container** within that storage account. 

Let me know if further clarification is needed.

**Comment by kaushikCanada** [comment]
Thank you Olivia for your reply. So to clarify there are two storage blobs
we have here right? 1. cloud blob and  2. local on device blob
in phase 1 its talking about blob1 and in LOCAL_STORAGE_ACCOUNT_NAME we
need to give blob2?  do they need to be same to be in sync?

**Comment by oliviajain** [comment]
Not quite. [Containers organize sets of blobs - see the docs here](https://docs.microsoft.com/en-us/azure/storage/blobs/storage-blobs-introduction#blob-storage-resources). In phase 1, you create the storage account (and a container which contains blobs). You would like to select the LOCAL_STORAGE_ACCOUNT_NAME you created for the container also in phase 1.

**Comment by kaushikCanada** [comment]
i see. then where do i put the values for local blob storage? like the
azureiotblobstorage module. where is that being used?

**Comment by oliviajain** [comment]
- cloudStorageConnectionString: [change $MY_STORAGE_CONNECTION_STRING to storage account connection string](https://github.com/Azure-Samples/onnxruntime-iot-edge/blob/0c3cf9f821caaaf06e212a7d78a739d75f89c1ca/deployment.template.json#L182)
- LOCAL_STORAGE_ACCOUNT_NAME/ KEY: [change values](https://github.com/Azure-Samples/onnxruntime-iot-edge/blob/0c3cf9f821caaaf06e212a7d78a739d75f89c1ca/deployment.template.json#L146)
- block_blob_service: [local blob storage connection string](https://github.com/Azure-Samples/onnxruntime-iot-edge/blob/0c3cf9f821caaaf06e212a7d78a739d75f89c1ca/modules/InferenceModule/main.py#L72) - the container is the "explicit storage endpoint" mentioned in the instructions
